<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransactionAggregation.Application\TransactionAggregation.Application.csproj" />
    <ProjectReference Include="..\TransactionAggregtion.Domain\TransactionAggregtion.Domain.csproj" />
  </ItemGroup>

</Project>
